name: deploy storybook

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: action/checkout@v3

      - name: Setup NodeJs
        uses: action/setup-node@v3
        with:
          node-version: 16

      - run: npm ci
      - run: npm run build-storybook

      - name: Deploy storybook
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
